powershell -Command "(Get-Content %phpPath%\php.ini) -replace ';?(max_execution_time)\s?=(.*)', '$1 = %php_max_execution_time%' | Out-File -Encoding \"UTF8\" %phpPath%\php.ini"
powershell -Command "(Get-Content %phpPath%\php.ini) -replace ';?(max_input_time)\s?=(.*)', '$1 = %php_max_input_time%' | Out-File -Encoding \"UTF8\" %phpPath%\php.ini"
powershell -Command "(Get-Content %phpPath%\php.ini) -replace ';?(memory_limit)\s?=(.*)', '$1 = %php_memory_limit%' | Out-File -Encoding \"UTF8\" %phpPath%\php.ini"
powershell -Command "(Get-Content %phpPath%\php.ini) -replace ';?(post_max_size)\s?=(.*)', '$1 = %php_post_max_size%' | Out-File -Encoding \"UTF8\" %phpPath%\php.ini"
powershell -Command "(Get-Content %phpPath%\php.ini) -replace ';?(upload_max_filesize)\s?=(.*)', '$1 = %php_upload_max_filesize%' | Out-File -Encoding \"UTF8\" %phpPath%\php.ini"

powershell -Command "(Get-Content %phpPath%\php.ini) -replace ';?(extension_dir)\s?=(.*)', '$1 = \"%php_extension_dir%\"' | Out-File -Encoding \"UTF8\" %phpPath%\php.ini"

powershell -Command "(Get-Content %phpPath%\php.ini) -replace ';extension=bz2', 'extension=bz2' | Out-File -Encoding \"UTF8\" %phpPath%\php.ini"
powershell -Command "(Get-Content %phpPath%\php.ini) -replace ';extension=curl', 'extension=curl' | Out-File -Encoding \"UTF8\" %phpPath%\php.ini"
powershell -Command "(Get-Content %phpPath%\php.ini) -replace ';extension=fileinfo', 'extension=fileinfo' | Out-File -Encoding \"UTF8\" %phpPath%\php.ini"
powershell -Command "(Get-Content %phpPath%\php.ini) -replace ';extension=gd', 'extension=gd' | Out-File -Encoding \"UTF8\" %phpPath%\php.ini"
powershell -Command "(Get-Content %phpPath%\php.ini) -replace ';extension=intl', 'extension=intl' | Out-File -Encoding \"UTF8\" %phpPath%\php.ini"
powershell -Command "(Get-Content %phpPath%\php.ini) -replace ';extension=ldap', 'extension=ldap' | Out-File -Encoding \"UTF8\" %phpPath%\php.ini"
powershell -Command "(Get-Content %phpPath%\php.ini) -replace ';extension=mbstring', 'extension=mbstring' | Out-File -Encoding \"UTF8\" %phpPath%\php.ini"
powershell -Command "(Get-Content %phpPath%\php.ini) -replace ';extension=odbc', 'extension=odbc' | Out-File -Encoding \"UTF8\" %phpPath%\php.ini"
powershell -Command "(Get-Content %phpPath%\php.ini) -replace ';extension=openssl', 'extension=openssl' | Out-File -Encoding \"UTF8\" %phpPath%\php.ini"
powershell -Command "(Get-Content %phpPath%\php.ini) -replace ';extension=pdo_mysql', 'extension=pdo_mysql' | Out-File -Encoding \"UTF8\" %phpPath%\php.ini"
powershell -Command "(Get-Content %phpPath%\php.ini) -replace ';extension=pdo_pgsql', 'extension=pdo_pgsql' | Out-File -Encoding \"UTF8\" %phpPath%\php.ini"
powershell -Command "(Get-Content %phpPath%\php.ini) -replace ';extension=pdo_sqlite', 'extension=pdo_sqlite' | Out-File -Encoding \"UTF8\" %phpPath%\php.ini"
powershell -Command "(Get-Content %phpPath%\php.ini) -replace ';extension=pgsql', 'extension=pgsql' | Out-File -Encoding \"UTF8\" %phpPath%\php.ini"
powershell -Command "(Get-Content %phpPath%\php.ini) -replace ';extension=soap', 'extension=soap' | Out-File -Encoding \"UTF8\" %phpPath%\php.ini"
powershell -Command "(Get-Content %phpPath%\php.ini) -replace ';extension=sockets', 'extension=sockets' | Out-File -Encoding \"UTF8\" %phpPath%\php.ini"
powershell -Command "(Get-Content %phpPath%\php.ini) -replace ';extension=sqlite3', 'extension=sqlite3' | Out-File -Encoding \"UTF8\" %phpPath%\php.ini"
powershell -Command "(Get-Content %phpPath%\php.ini) -replace ';extension=xsl', 'extension=xsl' | Out-File -Encoding \"UTF8\" %phpPath%\php.ini"
powershell -Command "(Get-Content %phpPath%\php.ini) -replace ';extension=zip', 'extension=zip' | Out-File -Encoding \"UTF8\" %phpPath%\php.ini"

powershell -Command "(Get-Content %phpPath%\php.ini) -replace ';zend_extension=opcache', 'zend_extension=opcache' | Out-File -Encoding \"UTF8\" %phpPath%\php.ini"
