set sqlsrvOutputFile=%tmp%\sqlsrv.zip

powershell -Command "Invoke-WebRequest https://windows.php.net/downloads/pecl/releases/imagick/%imagickVersion%/php_imagick-%imagickVersion%-%minorVersion%-nts-%vc%-x64.zip -OutFile %sqlsrvOutputFile%"

call %mainPath%\7zip\7za e "%sqlsrvOutputFile%" -o"%tmp%\imagick" -y

move /y %tmp%\imagick\php_imagick.dll %phpPath%\ext\php_imagick.dll

move /y %tmp%\imagick\CORE_RL_bzlib_.dll %phpPath%\CORE_RL_bzlib_.dll
move /y %tmp%\imagick\CORE_RL_cairo_.dll %phpPath%\CORE_RL_cairo_.dll
move /y %tmp%\imagick\CORE_RL_exr_.dll %phpPath%\CORE_RL_exr_.dll
move /y %tmp%\imagick\CORE_RL_flif_.dll %phpPath%\CORE_RL_flif_.dll
move /y %tmp%\imagick\CORE_RL_freetype_.dll %phpPath%\CORE_RL_freetype_.dll
move /y %tmp%\imagick\CORE_RL_fribidi_.dll %phpPath%\CORE_RL_fribidi_.dll
move /y %tmp%\imagick\CORE_RL_glib_.dll %phpPath%\CORE_RL_glib_.dll
move /y %tmp%\imagick\CORE_RL_harfbuzz_.dll %phpPath%\CORE_RL_harfbuzz_.dll
move /y %tmp%\imagick\CORE_RL_jp2_.dll %phpPath%\CORE_RL_jp2_.dll
move /y %tmp%\imagick\CORE_RL_jpeg-turbo_.dll %phpPath%\CORE_RL_jpeg-turbo_.dll
move /y %tmp%\imagick\CORE_RL_jpeg-xl_.dll %phpPath%\CORE_RL_jpeg-xl_.dll
move /y %tmp%\imagick\CORE_RL_lcms_.dll %phpPath%\CORE_RL_lcms_.dll
move /y %tmp%\imagick\CORE_RL_libheif_.dll %phpPath%\CORE_RL_libheif_.dll
move /y %tmp%\imagick\CORE_RL_liblzma_.dll %phpPath%\CORE_RL_liblzma_.dll
move /y %tmp%\imagick\CORE_RL_libraw_.dll %phpPath%\CORE_RL_libraw_.dll
move /y %tmp%\imagick\CORE_RL_librsvg_.dll %phpPath%\CORE_RL_librsvg_.dll
move /y %tmp%\imagick\CORE_RL_libxml_.dll %phpPath%\CORE_RL_libxml_.dll
move /y %tmp%\imagick\CORE_RL_libzip_.dll %phpPath%\CORE_RL_libzip_.dll
move /y %tmp%\imagick\CORE_RL_lqr_.dll %phpPath%\CORE_RL_lqr_.dll
move /y %tmp%\imagick\CORE_RL_Magick++_.dll %phpPath%\CORE_RL_Magick++_.dll
move /y %tmp%\imagick\CORE_RL_MagickCore_.dll %phpPath%\CORE_RL_MagickCore_.dll
move /y %tmp%\imagick\CORE_RL_MagickWand_.dll %phpPath%\CORE_RL_MagickWand_.dll
move /y %tmp%\imagick\CORE_RL_openjpeg_.dll %phpPath%\CORE_RL_openjpeg_.dll
move /y %tmp%\imagick\CORE_RL_pango_.dll %phpPath%\CORE_RL_pango_.dll
move /y %tmp%\imagick\CORE_RL_png_.dll %phpPath%\CORE_RL_png_.dll
move /y %tmp%\imagick\CORE_RL_tiff_.dll %phpPath%\CORE_RL_tiff_.dll
move /y %tmp%\imagick\CORE_RL_webp_.dll %phpPath%\CORE_RL_webp_.dll
move /y %tmp%\imagick\CORE_RL_zlib_.dll %phpPath%\CORE_RL_zlib_.dll
move /y %tmp%\imagick\FILTER_analyze_.dll %phpPath%\FILTER_analyze_.dll
move /y %tmp%\imagick\IM_MOD_RL_aai_.dll %phpPath%\IM_MOD_RL_aai_.dll
move /y %tmp%\imagick\IM_MOD_RL_art_.dll %phpPath%\IM_MOD_RL_art_.dll
move /y %tmp%\imagick\IM_MOD_RL_ashlar_.dll %phpPath%\IM_MOD_RL_ashlar_.dll
move /y %tmp%\imagick\IM_MOD_RL_avs_.dll %phpPath%\IM_MOD_RL_avs_.dll
move /y %tmp%\imagick\IM_MOD_RL_bgr_.dll %phpPath%\IM_MOD_RL_bgr_.dll
move /y %tmp%\imagick\IM_MOD_RL_bmp_.dll %phpPath%\IM_MOD_RL_bmp_.dll
move /y %tmp%\imagick\IM_MOD_RL_braille_.dll %phpPath%\IM_MOD_RL_braille_.dll
move /y %tmp%\imagick\IM_MOD_RL_cals_.dll %phpPath%\IM_MOD_RL_cals_.dll
move /y %tmp%\imagick\IM_MOD_RL_caption_.dll %phpPath%\IM_MOD_RL_caption_.dll
move /y %tmp%\imagick\IM_MOD_RL_cin_.dll %phpPath%\IM_MOD_RL_cin_.dll
move /y %tmp%\imagick\IM_MOD_RL_cip_.dll %phpPath%\IM_MOD_RL_cip_.dll
move /y %tmp%\imagick\IM_MOD_RL_clip_.dll %phpPath%\IM_MOD_RL_clip_.dll
move /y %tmp%\imagick\IM_MOD_RL_clipboard_.dll %phpPath%\IM_MOD_RL_clipboard_.dll
move /y %tmp%\imagick\IM_MOD_RL_cmyk_.dll %phpPath%\IM_MOD_RL_cmyk_.dll
move /y %tmp%\imagick\IM_MOD_RL_cube_.dll %phpPath%\IM_MOD_RL_cube_.dll
move /y %tmp%\imagick\IM_MOD_RL_cut_.dll %phpPath%\IM_MOD_RL_cut_.dll
move /y %tmp%\imagick\IM_MOD_RL_dcm_.dll %phpPath%\IM_MOD_RL_dcm_.dll
move /y %tmp%\imagick\IM_MOD_RL_dds_.dll %phpPath%\IM_MOD_RL_dds_.dll
move /y %tmp%\imagick\IM_MOD_RL_debug_.dll %phpPath%\IM_MOD_RL_debug_.dll
move /y %tmp%\imagick\IM_MOD_RL_dib_.dll %phpPath%\IM_MOD_RL_dib_.dll
move /y %tmp%\imagick\IM_MOD_RL_djvu_.dll %phpPath%\IM_MOD_RL_djvu_.dll
move /y %tmp%\imagick\IM_MOD_RL_dng_.dll %phpPath%\IM_MOD_RL_dng_.dll
move /y %tmp%\imagick\IM_MOD_RL_dot_.dll %phpPath%\IM_MOD_RL_dot_.dll
move /y %tmp%\imagick\IM_MOD_RL_dps_.dll %phpPath%\IM_MOD_RL_dps_.dll
move /y %tmp%\imagick\IM_MOD_RL_dpx_.dll %phpPath%\IM_MOD_RL_dpx_.dll
move /y %tmp%\imagick\IM_MOD_RL_emf_.dll %phpPath%\IM_MOD_RL_emf_.dll
move /y %tmp%\imagick\IM_MOD_RL_ept_.dll %phpPath%\IM_MOD_RL_ept_.dll
move /y %tmp%\imagick\IM_MOD_RL_exr_.dll %phpPath%\IM_MOD_RL_exr_.dll
move /y %tmp%\imagick\IM_MOD_RL_farbfeld_.dll %phpPath%\IM_MOD_RL_farbfeld_.dll
move /y %tmp%\imagick\IM_MOD_RL_fax_.dll %phpPath%\IM_MOD_RL_fax_.dll
move /y %tmp%\imagick\IM_MOD_RL_fits_.dll %phpPath%\IM_MOD_RL_fits_.dll
move /y %tmp%\imagick\IM_MOD_RL_fl32_.dll %phpPath%\IM_MOD_RL_fl32_.dll
move /y %tmp%\imagick\IM_MOD_RL_flif_.dll %phpPath%\IM_MOD_RL_flif_.dll
move /y %tmp%\imagick\IM_MOD_RL_fpx_.dll %phpPath%\IM_MOD_RL_fpx_.dll
move /y %tmp%\imagick\IM_MOD_RL_gif_.dll %phpPath%\IM_MOD_RL_gif_.dll
move /y %tmp%\imagick\IM_MOD_RL_gradient_.dll %phpPath%\IM_MOD_RL_gradient_.dll
move /y %tmp%\imagick\IM_MOD_RL_gray_.dll %phpPath%\IM_MOD_RL_gray_.dll
move /y %tmp%\imagick\IM_MOD_RL_hald_.dll %phpPath%\IM_MOD_RL_hald_.dll
move /y %tmp%\imagick\IM_MOD_RL_hdr_.dll %phpPath%\IM_MOD_RL_hdr_.dll
move /y %tmp%\imagick\IM_MOD_RL_heic_.dll %phpPath%\IM_MOD_RL_heic_.dll
move /y %tmp%\imagick\IM_MOD_RL_histogram_.dll %phpPath%\IM_MOD_RL_histogram_.dll
move /y %tmp%\imagick\IM_MOD_RL_hrz_.dll %phpPath%\IM_MOD_RL_hrz_.dll
move /y %tmp%\imagick\IM_MOD_RL_html_.dll %phpPath%\IM_MOD_RL_html_.dll
move /y %tmp%\imagick\IM_MOD_RL_icon_.dll %phpPath%\IM_MOD_RL_icon_.dll
move /y %tmp%\imagick\IM_MOD_RL_info_.dll %phpPath%\IM_MOD_RL_info_.dll
move /y %tmp%\imagick\IM_MOD_RL_inline_.dll %phpPath%\IM_MOD_RL_inline_.dll
move /y %tmp%\imagick\IM_MOD_RL_ipl_.dll %phpPath%\IM_MOD_RL_ipl_.dll
move /y %tmp%\imagick\IM_MOD_RL_jbig_.dll %phpPath%\IM_MOD_RL_jbig_.dll
move /y %tmp%\imagick\IM_MOD_RL_jnx_.dll %phpPath%\IM_MOD_RL_jnx_.dll
move /y %tmp%\imagick\IM_MOD_RL_jp2_.dll %phpPath%\IM_MOD_RL_jp2_.dll
move /y %tmp%\imagick\IM_MOD_RL_jpeg_.dll %phpPath%\IM_MOD_RL_jpeg_.dll
move /y %tmp%\imagick\IM_MOD_RL_json_.dll %phpPath%\IM_MOD_RL_json_.dll
move /y %tmp%\imagick\IM_MOD_RL_jxl_.dll %phpPath%\IM_MOD_RL_jxl_.dll
move /y %tmp%\imagick\IM_MOD_RL_kernel_.dll %phpPath%\IM_MOD_RL_kernel_.dll
move /y %tmp%\imagick\IM_MOD_RL_label_.dll %phpPath%\IM_MOD_RL_label_.dll
move /y %tmp%\imagick\IM_MOD_RL_mac_.dll %phpPath%\IM_MOD_RL_mac_.dll
move /y %tmp%\imagick\IM_MOD_RL_magick_.dll %phpPath%\IM_MOD_RL_magick_.dll
move /y %tmp%\imagick\IM_MOD_RL_map_.dll %phpPath%\IM_MOD_RL_map_.dll
move /y %tmp%\imagick\IM_MOD_RL_mask_.dll %phpPath%\IM_MOD_RL_mask_.dll
move /y %tmp%\imagick\IM_MOD_RL_mat_.dll %phpPath%\IM_MOD_RL_mat_.dll
move /y %tmp%\imagick\IM_MOD_RL_matte_.dll %phpPath%\IM_MOD_RL_matte_.dll
move /y %tmp%\imagick\IM_MOD_RL_meta_.dll %phpPath%\IM_MOD_RL_meta_.dll
move /y %tmp%\imagick\IM_MOD_RL_miff_.dll %phpPath%\IM_MOD_RL_miff_.dll
move /y %tmp%\imagick\IM_MOD_RL_mono_.dll %phpPath%\IM_MOD_RL_mono_.dll
move /y %tmp%\imagick\IM_MOD_RL_mpc_.dll %phpPath%\IM_MOD_RL_mpc_.dll
move /y %tmp%\imagick\IM_MOD_RL_mpr_.dll %phpPath%\IM_MOD_RL_mpr_.dll
move /y %tmp%\imagick\IM_MOD_RL_msl_.dll %phpPath%\IM_MOD_RL_msl_.dll
move /y %tmp%\imagick\IM_MOD_RL_mtv_.dll %phpPath%\IM_MOD_RL_mtv_.dll
move /y %tmp%\imagick\IM_MOD_RL_mvg_.dll %phpPath%\IM_MOD_RL_mvg_.dll
move /y %tmp%\imagick\IM_MOD_RL_null_.dll %phpPath%\IM_MOD_RL_null_.dll
move /y %tmp%\imagick\IM_MOD_RL_ora_.dll %phpPath%\IM_MOD_RL_ora_.dll
move /y %tmp%\imagick\IM_MOD_RL_otb_.dll %phpPath%\IM_MOD_RL_otb_.dll
move /y %tmp%\imagick\IM_MOD_RL_palm_.dll %phpPath%\IM_MOD_RL_palm_.dll
move /y %tmp%\imagick\IM_MOD_RL_pango_.dll %phpPath%\IM_MOD_RL_pango_.dll
move /y %tmp%\imagick\IM_MOD_RL_pattern_.dll %phpPath%\IM_MOD_RL_pattern_.dll
move /y %tmp%\imagick\IM_MOD_RL_pcd_.dll %phpPath%\IM_MOD_RL_pcd_.dll
move /y %tmp%\imagick\IM_MOD_RL_pcl_.dll %phpPath%\IM_MOD_RL_pcl_.dll
move /y %tmp%\imagick\IM_MOD_RL_pcx_.dll %phpPath%\IM_MOD_RL_pcx_.dll
move /y %tmp%\imagick\IM_MOD_RL_pdb_.dll %phpPath%\IM_MOD_RL_pdb_.dll
move /y %tmp%\imagick\IM_MOD_RL_pdf_.dll %phpPath%\IM_MOD_RL_pdf_.dll
move /y %tmp%\imagick\IM_MOD_RL_pes_.dll %phpPath%\IM_MOD_RL_pes_.dll
move /y %tmp%\imagick\IM_MOD_RL_pgx_.dll %phpPath%\IM_MOD_RL_pgx_.dll
move /y %tmp%\imagick\IM_MOD_RL_pict_.dll %phpPath%\IM_MOD_RL_pict_.dll
move /y %tmp%\imagick\IM_MOD_RL_pix_.dll %phpPath%\IM_MOD_RL_pix_.dll
move /y %tmp%\imagick\IM_MOD_RL_plasma_.dll %phpPath%\IM_MOD_RL_plasma_.dll
move /y %tmp%\imagick\IM_MOD_RL_png_.dll %phpPath%\IM_MOD_RL_png_.dll
move /y %tmp%\imagick\IM_MOD_RL_pnm_.dll %phpPath%\IM_MOD_RL_pnm_.dll
move /y %tmp%\imagick\IM_MOD_RL_ps2_.dll %phpPath%\IM_MOD_RL_ps2_.dll
move /y %tmp%\imagick\IM_MOD_RL_ps3_.dll %phpPath%\IM_MOD_RL_ps3_.dll
move /y %tmp%\imagick\IM_MOD_RL_ps_.dll %phpPath%\IM_MOD_RL_ps_.dll
move /y %tmp%\imagick\IM_MOD_RL_psd_.dll %phpPath%\IM_MOD_RL_psd_.dll
move /y %tmp%\imagick\IM_MOD_RL_pwp_.dll %phpPath%\IM_MOD_RL_pwp_.dll
move /y %tmp%\imagick\IM_MOD_RL_raw_.dll %phpPath%\IM_MOD_RL_raw_.dll
move /y %tmp%\imagick\IM_MOD_RL_rgb_.dll %phpPath%\IM_MOD_RL_rgb_.dll
move /y %tmp%\imagick\IM_MOD_RL_rgf_.dll %phpPath%\IM_MOD_RL_rgf_.dll
move /y %tmp%\imagick\IM_MOD_RL_rla_.dll %phpPath%\IM_MOD_RL_rla_.dll
move /y %tmp%\imagick\IM_MOD_RL_rle_.dll %phpPath%\IM_MOD_RL_rle_.dll
move /y %tmp%\imagick\IM_MOD_RL_scr_.dll %phpPath%\IM_MOD_RL_scr_.dll
move /y %tmp%\imagick\IM_MOD_RL_screenshot_.dll %phpPath%\IM_MOD_RL_screenshot_.dll
move /y %tmp%\imagick\IM_MOD_RL_sct_.dll %phpPath%\IM_MOD_RL_sct_.dll
move /y %tmp%\imagick\IM_MOD_RL_sfw_.dll %phpPath%\IM_MOD_RL_sfw_.dll
move /y %tmp%\imagick\IM_MOD_RL_sgi_.dll %phpPath%\IM_MOD_RL_sgi_.dll
move /y %tmp%\imagick\IM_MOD_RL_sixel_.dll %phpPath%\IM_MOD_RL_sixel_.dll
move /y %tmp%\imagick\IM_MOD_RL_stegano_.dll %phpPath%\IM_MOD_RL_stegano_.dll
move /y %tmp%\imagick\IM_MOD_RL_sun_.dll %phpPath%\IM_MOD_RL_sun_.dll
move /y %tmp%\imagick\IM_MOD_RL_svg_.dll %phpPath%\IM_MOD_RL_svg_.dll
move /y %tmp%\imagick\IM_MOD_RL_tga_.dll %phpPath%\IM_MOD_RL_tga_.dll
move /y %tmp%\imagick\IM_MOD_RL_thumbnail_.dll %phpPath%\IM_MOD_RL_thumbnail_.dll
move /y %tmp%\imagick\IM_MOD_RL_tiff_.dll %phpPath%\IM_MOD_RL_tiff_.dll
move /y %tmp%\imagick\IM_MOD_RL_tile_.dll %phpPath%\IM_MOD_RL_tile_.dll
move /y %tmp%\imagick\IM_MOD_RL_tim2_.dll %phpPath%\IM_MOD_RL_tim2_.dll
move /y %tmp%\imagick\IM_MOD_RL_tim_.dll %phpPath%\IM_MOD_RL_tim_.dll
move /y %tmp%\imagick\IM_MOD_RL_ttf_.dll %phpPath%\IM_MOD_RL_ttf_.dll
move /y %tmp%\imagick\IM_MOD_RL_txt_.dll %phpPath%\IM_MOD_RL_txt_.dll
move /y %tmp%\imagick\IM_MOD_RL_uil_.dll %phpPath%\IM_MOD_RL_uil_.dll
move /y %tmp%\imagick\IM_MOD_RL_url_.dll %phpPath%\IM_MOD_RL_url_.dll
move /y %tmp%\imagick\IM_MOD_RL_uyvy_.dll %phpPath%\IM_MOD_RL_uyvy_.dll
move /y %tmp%\imagick\IM_MOD_RL_vicar_.dll %phpPath%\IM_MOD_RL_vicar_.dll
move /y %tmp%\imagick\IM_MOD_RL_vid_.dll %phpPath%\IM_MOD_RL_vid_.dll
move /y %tmp%\imagick\IM_MOD_RL_video_.dll %phpPath%\IM_MOD_RL_video_.dll
move /y %tmp%\imagick\IM_MOD_RL_viff_.dll %phpPath%\IM_MOD_RL_viff_.dll
move /y %tmp%\imagick\IM_MOD_RL_vips_.dll %phpPath%\IM_MOD_RL_vips_.dll
move /y %tmp%\imagick\IM_MOD_RL_wbmp_.dll %phpPath%\IM_MOD_RL_wbmp_.dll
move /y %tmp%\imagick\IM_MOD_RL_webp_.dll %phpPath%\IM_MOD_RL_webp_.dll
move /y %tmp%\imagick\IM_MOD_RL_wpg_.dll %phpPath%\IM_MOD_RL_wpg_.dll
move /y %tmp%\imagick\IM_MOD_RL_xbm_.dll %phpPath%\IM_MOD_RL_xbm_.dll
move /y %tmp%\imagick\IM_MOD_RL_xc_.dll %phpPath%\IM_MOD_RL_xc_.dll
move /y %tmp%\imagick\IM_MOD_RL_xcf_.dll %phpPath%\IM_MOD_RL_xcf_.dll
move /y %tmp%\imagick\IM_MOD_RL_xpm_.dll %phpPath%\IM_MOD_RL_xpm_.dll
move /y %tmp%\imagick\IM_MOD_RL_xps_.dll %phpPath%\IM_MOD_RL_xps_.dll
move /y %tmp%\imagick\IM_MOD_RL_xtrn_.dll %phpPath%\IM_MOD_RL_xtrn_.dll
move /y %tmp%\imagick\IM_MOD_RL_yaml_.dll %phpPath%\IM_MOD_RL_yaml_.dll
move /y %tmp%\imagick\IM_MOD_RL_ycbcr_.dll %phpPath%\IM_MOD_RL_ycbcr_.dll
move /y %tmp%\imagick\IM_MOD_RL_yuv_.dll %phpPath%\IM_MOD_RL_yuv_.dll
move /y %tmp%\imagick\ImageMagickObject.dll %phpPath%\ImageMagickObject.dll
move /y %tmp%\imagick\X11.dll %phpPath%\X11.dll
move /y %tmp%\imagick\Xext.dll %phpPath%\Xext.dll
